// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entities.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getAdAccount = `-- name: GetAdAccount :one
SELECT ad_accounts.id, ad_accounts.organization_id, ad_accounts.integration_id, ad_accounts.provider, ad_accounts.external_id, ad_accounts.name, ad_accounts.currency, ad_accounts.timezone, ad_accounts.status, ad_accounts.sync_enabled, ad_accounts.raw, ad_accounts.created_at, ad_accounts.updated_at, integrations.status AS integration_status
FROM ad_accounts
LEFT JOIN integrations ON integrations.id = ad_accounts.integration_id
WHERE ad_accounts.organization_id = $1 AND ad_accounts.id = $2
`

type GetAdAccountParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetAdAccountRow struct {
	AdAccount         AdAccount          `json:"ad_account"`
	IntegrationStatus *IntegrationStatus `json:"integration_status"`
}

func (q *Queries) GetAdAccount(ctx context.Context, arg GetAdAccountParams) (GetAdAccountRow, error) {
	row := q.db.QueryRow(ctx, getAdAccount, arg.OrganizationID, arg.ID)
	var i GetAdAccountRow
	err := row.Scan(
		&i.AdAccount.ID,
		&i.AdAccount.OrganizationID,
		&i.AdAccount.IntegrationID,
		&i.AdAccount.Provider,
		&i.AdAccount.ExternalID,
		&i.AdAccount.Name,
		&i.AdAccount.Currency,
		&i.AdAccount.Timezone,
		&i.AdAccount.Status,
		&i.AdAccount.SyncEnabled,
		&i.AdAccount.Raw,
		&i.AdAccount.CreatedAt,
		&i.AdAccount.UpdatedAt,
		&i.IntegrationStatus,
	)
	return i, err
}

const getCampaign = `-- name: GetCampaign :one
SELECT campaigns.id, campaigns.organization_id, campaigns.account_id, campaigns.provider, campaigns.external_id, campaigns.name, campaigns.status, campaigns.objective, campaigns.daily_budget_micros, campaigns.lifetime_budget_micros, campaigns.raw, campaigns.created_at, campaigns.updated_at, ad_accounts.currency, ad_accounts.timezone
FROM campaigns
JOIN ad_accounts ON ad_accounts.id = campaigns.account_id
WHERE campaigns.organization_id = $1 AND campaigns.id = $2
`

type GetCampaignParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

type GetCampaignRow struct {
	Campaign Campaign `json:"campaign"`
	Currency string   `json:"currency"`
	Timezone string   `json:"timezone"`
}

func (q *Queries) GetCampaign(ctx context.Context, arg GetCampaignParams) (GetCampaignRow, error) {
	row := q.db.QueryRow(ctx, getCampaign, arg.OrganizationID, arg.ID)
	var i GetCampaignRow
	err := row.Scan(
		&i.Campaign.ID,
		&i.Campaign.OrganizationID,
		&i.Campaign.AccountID,
		&i.Campaign.Provider,
		&i.Campaign.ExternalID,
		&i.Campaign.Name,
		&i.Campaign.Status,
		&i.Campaign.Objective,
		&i.Campaign.DailyBudgetMicros,
		&i.Campaign.LifetimeBudgetMicros,
		&i.Campaign.Raw,
		&i.Campaign.CreatedAt,
		&i.Campaign.UpdatedAt,
		&i.Currency,
		&i.Timezone,
	)
	return i, err
}

const listAccountSyncStates = `-- name: ListAccountSyncStates :many
SELECT account_id, scope, organization_id, provider, last_synced_at, updated_at FROM ad_account_sync_state
WHERE organization_id = $1
ORDER BY account_id, scope
`

func (q *Queries) ListAccountSyncStates(ctx context.Context, organizationID uuid.UUID) ([]AdAccountSyncState, error) {
	rows, err := q.db.Query(ctx, listAccountSyncStates, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdAccountSyncState{}
	for rows.Next() {
		var i AdAccountSyncState
		if err := rows.Scan(
			&i.AccountID,
			&i.Scope,
			&i.OrganizationID,
			&i.Provider,
			&i.LastSyncedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdAccounts = `-- name: ListAdAccounts :many

SELECT ad_accounts.id, ad_accounts.organization_id, ad_accounts.integration_id, ad_accounts.provider, ad_accounts.external_id, ad_accounts.name, ad_accounts.currency, ad_accounts.timezone, ad_accounts.status, ad_accounts.sync_enabled, ad_accounts.raw, ad_accounts.created_at, ad_accounts.updated_at, integrations.status AS integration_status
FROM ad_accounts
LEFT JOIN integrations ON integrations.id = ad_accounts.integration_id
WHERE ad_accounts.organization_id = $1
  AND ($2::ad_provider IS NULL OR ad_accounts.provider = $2)
ORDER BY ad_accounts.provider, ad_accounts.name, ad_accounts.id
`

type ListAdAccountsParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	Provider       *AdProvider `json:"provider"`
}

type ListAdAccountsRow struct {
	AdAccount         AdAccount          `json:"ad_account"`
	IntegrationStatus *IntegrationStatus `json:"integration_status"`
}

// Canonical entities (internal/entities). Writes from sync jobs use pgx batch
// upserts in internal/entities/store.go; these are the read paths for the API.
func (q *Queries) ListAdAccounts(ctx context.Context, arg ListAdAccountsParams) ([]ListAdAccountsRow, error) {
	rows, err := q.db.Query(ctx, listAdAccounts, arg.OrganizationID, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdAccountsRow{}
	for rows.Next() {
		var i ListAdAccountsRow
		if err := rows.Scan(
			&i.AdAccount.ID,
			&i.AdAccount.OrganizationID,
			&i.AdAccount.IntegrationID,
			&i.AdAccount.Provider,
			&i.AdAccount.ExternalID,
			&i.AdAccount.Name,
			&i.AdAccount.Currency,
			&i.AdAccount.Timezone,
			&i.AdAccount.Status,
			&i.AdAccount.SyncEnabled,
			&i.AdAccount.Raw,
			&i.AdAccount.CreatedAt,
			&i.AdAccount.UpdatedAt,
			&i.IntegrationStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdGroups = `-- name: ListAdGroups :many
SELECT ad_groups.id, ad_groups.organization_id, ad_groups.account_id, ad_groups.campaign_id, ad_groups.provider, ad_groups.external_id, ad_groups.name, ad_groups.status, ad_groups.daily_budget_micros, ad_groups.raw, ad_groups.created_at, ad_groups.updated_at,
       campaigns.name AS campaign_name, campaigns.external_id AS campaign_external_id,
       ad_accounts.name AS account_name, ad_accounts.currency, ad_accounts.timezone,
       count(*) OVER () AS total
FROM ad_groups
JOIN campaigns ON campaigns.id = ad_groups.campaign_id
JOIN ad_accounts ON ad_accounts.id = ad_groups.account_id
WHERE ad_groups.organization_id = $1
  AND ($2::uuid IS NULL OR ad_groups.account_id = $2)
  AND ($3::ad_provider IS NULL OR ad_groups.provider = $3)
  AND ($4::ad_entity_status IS NULL OR ad_groups.status = $4)
  AND ($5::uuid IS NULL OR ad_groups.campaign_id = $5)
  AND ($6::text IS NULL
       OR ad_groups.name ILIKE '%' || $6 || '%'
       OR ad_groups.external_id = $7)
ORDER BY ad_groups.name, ad_groups.id
LIMIT $9 OFFSET $8
`

type ListAdGroupsParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	AccountID      *uuid.UUID      `json:"account_id"`
	Provider       *AdProvider     `json:"provider"`
	Status         *AdEntityStatus `json:"status"`
	CampaignID     *uuid.UUID      `json:"campaign_id"`
	Search         *string         `json:"search"`
	SearchExact    *string         `json:"search_exact"`
	RowOffset      int32           `json:"row_offset"`
	RowLimit       int32           `json:"row_limit"`
}

type ListAdGroupsRow struct {
	AdGroup            AdGroup `json:"ad_group"`
	CampaignName       string  `json:"campaign_name"`
	CampaignExternalID string  `json:"campaign_external_id"`
	AccountName        string  `json:"account_name"`
	Currency           string  `json:"currency"`
	Timezone           string  `json:"timezone"`
	Total              int64   `json:"total"`
}

func (q *Queries) ListAdGroups(ctx context.Context, arg ListAdGroupsParams) ([]ListAdGroupsRow, error) {
	rows, err := q.db.Query(ctx, listAdGroups,
		arg.OrganizationID,
		arg.AccountID,
		arg.Provider,
		arg.Status,
		arg.CampaignID,
		arg.Search,
		arg.SearchExact,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdGroupsRow{}
	for rows.Next() {
		var i ListAdGroupsRow
		if err := rows.Scan(
			&i.AdGroup.ID,
			&i.AdGroup.OrganizationID,
			&i.AdGroup.AccountID,
			&i.AdGroup.CampaignID,
			&i.AdGroup.Provider,
			&i.AdGroup.ExternalID,
			&i.AdGroup.Name,
			&i.AdGroup.Status,
			&i.AdGroup.DailyBudgetMicros,
			&i.AdGroup.Raw,
			&i.AdGroup.CreatedAt,
			&i.AdGroup.UpdatedAt,
			&i.CampaignName,
			&i.CampaignExternalID,
			&i.AccountName,
			&i.Currency,
			&i.Timezone,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAds = `-- name: ListAds :many
SELECT ads.id, ads.organization_id, ads.account_id, ads.campaign_id, ads.ad_group_id, ads.provider, ads.external_id, ads.name, ads.status, ads.creative_external_id, ads.raw, ads.created_at, ads.updated_at,
       campaigns.name AS campaign_name, campaigns.external_id AS campaign_external_id,
       ad_groups.name AS ad_group_name, ad_groups.external_id AS ad_group_external_id,
       ad_accounts.name AS account_name, ad_accounts.currency, ad_accounts.timezone,
       creatives.id AS creative_id,
       count(*) OVER () AS total
FROM ads
JOIN campaigns ON campaigns.id = ads.campaign_id
JOIN ad_groups ON ad_groups.id = ads.ad_group_id
JOIN ad_accounts ON ad_accounts.id = ads.account_id
LEFT JOIN creatives ON creatives.account_id = ads.account_id
                   AND creatives.external_id = ads.creative_external_id
WHERE ads.organization_id = $1
  AND ($2::uuid IS NULL OR ads.account_id = $2)
  AND ($3::ad_provider IS NULL OR ads.provider = $3)
  AND ($4::ad_entity_status IS NULL OR ads.status = $4)
  AND ($5::uuid IS NULL OR ads.campaign_id = $5)
  AND ($6::uuid IS NULL OR ads.ad_group_id = $6)
  AND ($7::text IS NULL
       OR ads.name ILIKE '%' || $7 || '%'
       OR ads.external_id = $8)
ORDER BY ads.name, ads.id
LIMIT $10 OFFSET $9
`

type ListAdsParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	AccountID      *uuid.UUID      `json:"account_id"`
	Provider       *AdProvider     `json:"provider"`
	Status         *AdEntityStatus `json:"status"`
	CampaignID     *uuid.UUID      `json:"campaign_id"`
	AdGroupID      *uuid.UUID      `json:"ad_group_id"`
	Search         *string         `json:"search"`
	SearchExact    *string         `json:"search_exact"`
	RowOffset      int32           `json:"row_offset"`
	RowLimit       int32           `json:"row_limit"`
}

type ListAdsRow struct {
	Ad                 Ad         `json:"ad"`
	CampaignName       string     `json:"campaign_name"`
	CampaignExternalID string     `json:"campaign_external_id"`
	AdGroupName        string     `json:"ad_group_name"`
	AdGroupExternalID  string     `json:"ad_group_external_id"`
	AccountName        string     `json:"account_name"`
	Currency           string     `json:"currency"`
	Timezone           string     `json:"timezone"`
	CreativeID         *uuid.UUID `json:"creative_id"`
	Total              int64      `json:"total"`
}

func (q *Queries) ListAds(ctx context.Context, arg ListAdsParams) ([]ListAdsRow, error) {
	rows, err := q.db.Query(ctx, listAds,
		arg.OrganizationID,
		arg.AccountID,
		arg.Provider,
		arg.Status,
		arg.CampaignID,
		arg.AdGroupID,
		arg.Search,
		arg.SearchExact,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdsRow{}
	for rows.Next() {
		var i ListAdsRow
		if err := rows.Scan(
			&i.Ad.ID,
			&i.Ad.OrganizationID,
			&i.Ad.AccountID,
			&i.Ad.CampaignID,
			&i.Ad.AdGroupID,
			&i.Ad.Provider,
			&i.Ad.ExternalID,
			&i.Ad.Name,
			&i.Ad.Status,
			&i.Ad.CreativeExternalID,
			&i.Ad.Raw,
			&i.Ad.CreatedAt,
			&i.Ad.UpdatedAt,
			&i.CampaignName,
			&i.CampaignExternalID,
			&i.AdGroupName,
			&i.AdGroupExternalID,
			&i.AccountName,
			&i.Currency,
			&i.Timezone,
			&i.CreativeID,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT campaigns.id, campaigns.organization_id, campaigns.account_id, campaigns.provider, campaigns.external_id, campaigns.name, campaigns.status, campaigns.objective, campaigns.daily_budget_micros, campaigns.lifetime_budget_micros, campaigns.raw, campaigns.created_at, campaigns.updated_at,
       ad_accounts.name AS account_name, ad_accounts.currency, ad_accounts.timezone,
       count(*) OVER () AS total
FROM campaigns
JOIN ad_accounts ON ad_accounts.id = campaigns.account_id
WHERE campaigns.organization_id = $1
  AND ($2::uuid IS NULL OR campaigns.account_id = $2)
  AND ($3::ad_provider IS NULL OR campaigns.provider = $3)
  AND ($4::ad_entity_status IS NULL OR campaigns.status = $4)
  AND ($5::uuid IS NULL OR campaigns.id = $5)
  AND ($6::text IS NULL
       OR campaigns.name ILIKE '%' || $6 || '%'
       OR campaigns.external_id = $7)
ORDER BY campaigns.name, campaigns.id
LIMIT $9 OFFSET $8
`

type ListCampaignsParams struct {
	OrganizationID uuid.UUID       `json:"organization_id"`
	AccountID      *uuid.UUID      `json:"account_id"`
	Provider       *AdProvider     `json:"provider"`
	Status         *AdEntityStatus `json:"status"`
	CampaignID     *uuid.UUID      `json:"campaign_id"`
	Search         *string         `json:"search"`
	SearchExact    *string         `json:"search_exact"`
	RowOffset      int32           `json:"row_offset"`
	RowLimit       int32           `json:"row_limit"`
}

type ListCampaignsRow struct {
	Campaign    Campaign `json:"campaign"`
	AccountName string   `json:"account_name"`
	Currency    string   `json:"currency"`
	Timezone    string   `json:"timezone"`
	Total       int64    `json:"total"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]ListCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listCampaigns,
		arg.OrganizationID,
		arg.AccountID,
		arg.Provider,
		arg.Status,
		arg.CampaignID,
		arg.Search,
		arg.SearchExact,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCampaignsRow{}
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.Campaign.ID,
			&i.Campaign.OrganizationID,
			&i.Campaign.AccountID,
			&i.Campaign.Provider,
			&i.Campaign.ExternalID,
			&i.Campaign.Name,
			&i.Campaign.Status,
			&i.Campaign.Objective,
			&i.Campaign.DailyBudgetMicros,
			&i.Campaign.LifetimeBudgetMicros,
			&i.Campaign.Raw,
			&i.Campaign.CreatedAt,
			&i.Campaign.UpdatedAt,
			&i.AccountName,
			&i.Currency,
			&i.Timezone,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreatives = `-- name: ListCreatives :many
SELECT creatives.id, creatives.organization_id, creatives.account_id, creatives.provider, creatives.external_id, creatives.name, creatives.type, creatives.thumbnail_url, creatives.raw, creatives.created_at, creatives.updated_at,
       ad_accounts.name AS account_name, ad_accounts.currency, ad_accounts.timezone,
       count(*) OVER () AS total
FROM creatives
JOIN ad_accounts ON ad_accounts.id = creatives.account_id
WHERE creatives.organization_id = $1
  AND ($2::uuid IS NULL OR creatives.account_id = $2)
  AND ($3::ad_provider IS NULL OR creatives.provider = $3)
  AND ($4::uuid IS NULL OR EXISTS (
        SELECT 1 FROM ads
        WHERE ads.campaign_id = $4
          AND ads.account_id = creatives.account_id
          AND ads.creative_external_id = creatives.external_id))
  AND ($5::text IS NULL
       OR creatives.name ILIKE '%' || $5 || '%'
       OR creatives.external_id = $6)
ORDER BY creatives.name, creatives.id
LIMIT $8 OFFSET $7
`

type ListCreativesParams struct {
	OrganizationID uuid.UUID   `json:"organization_id"`
	AccountID      *uuid.UUID  `json:"account_id"`
	Provider       *AdProvider `json:"provider"`
	CampaignID     *uuid.UUID  `json:"campaign_id"`
	Search         *string     `json:"search"`
	SearchExact    *string     `json:"search_exact"`
	RowOffset      int32       `json:"row_offset"`
	RowLimit       int32       `json:"row_limit"`
}

type ListCreativesRow struct {
	Creative    Creative `json:"creative"`
	AccountName string   `json:"account_name"`
	Currency    string   `json:"currency"`
	Timezone    string   `json:"timezone"`
	Total       int64    `json:"total"`
}

// campaign_id matches creatives used by at least one ad in that campaign.
func (q *Queries) ListCreatives(ctx context.Context, arg ListCreativesParams) ([]ListCreativesRow, error) {
	rows, err := q.db.Query(ctx, listCreatives,
		arg.OrganizationID,
		arg.AccountID,
		arg.Provider,
		arg.CampaignID,
		arg.Search,
		arg.SearchExact,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCreativesRow{}
	for rows.Next() {
		var i ListCreativesRow
		if err := rows.Scan(
			&i.Creative.ID,
			&i.Creative.OrganizationID,
			&i.Creative.AccountID,
			&i.Creative.Provider,
			&i.Creative.ExternalID,
			&i.Creative.Name,
			&i.Creative.Type,
			&i.Creative.ThumbnailUrl,
			&i.Creative.Raw,
			&i.Creative.CreatedAt,
			&i.Creative.UpdatedAt,
			&i.AccountName,
			&i.Currency,
			&i.Timezone,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAdAccountSyncEnabled = `-- name: SetAdAccountSyncEnabled :one
UPDATE ad_accounts
SET sync_enabled = $1, updated_at = now()
WHERE organization_id = $2 AND id = $3
RETURNING id, organization_id, integration_id, provider, external_id, name, currency, timezone, status, sync_enabled, raw, created_at, updated_at
`

type SetAdAccountSyncEnabledParams struct {
	SyncEnabled    bool      `json:"sync_enabled"`
	OrganizationID uuid.UUID `json:"organization_id"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) SetAdAccountSyncEnabled(ctx context.Context, arg SetAdAccountSyncEnabledParams) (AdAccount, error) {
	row := q.db.QueryRow(ctx, setAdAccountSyncEnabled, arg.SyncEnabled, arg.OrganizationID, arg.ID)
	var i AdAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.IntegrationID,
		&i.Provider,
		&i.ExternalID,
		&i.Name,
		&i.Currency,
		&i.Timezone,
		&i.Status,
		&i.SyncEnabled,
		&i.Raw,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
