// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countIntegrationAccounts = `-- name: CountIntegrationAccounts :many
SELECT integration_id, count(*)::bigint AS accounts, count(*) FILTER (WHERE sync_enabled)::bigint AS sync_enabled
FROM ad_accounts
WHERE organization_id = $1 AND integration_id IS NOT NULL
GROUP BY integration_id
`

type CountIntegrationAccountsRow struct {
	IntegrationID *uuid.UUID `json:"integration_id"`
	Accounts      int64      `json:"accounts"`
	SyncEnabled   int64      `json:"sync_enabled"`
}

func (q *Queries) CountIntegrationAccounts(ctx context.Context, organizationID uuid.UUID) ([]CountIntegrationAccountsRow, error) {
	rows, err := q.db.Query(ctx, countIntegrationAccounts, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountIntegrationAccountsRow{}
	for rows.Next() {
		var i CountIntegrationAccountsRow
		if err := rows.Scan(&i.IntegrationID, &i.Accounts, &i.SyncEnabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const disconnectIntegration = `-- name: DisconnectIntegration :exec
UPDATE integrations
SET status = 'disconnected',
    access_token_encrypted = NULL,
    refresh_token_encrypted = NULL,
    token_expires_at = NULL,
    disconnected_at = now(),
    updated_at = now()
WHERE id = $1 AND organization_id = $2
`

type DisconnectIntegrationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) DisconnectIntegration(ctx context.Context, arg DisconnectIntegrationParams) error {
	_, err := q.db.Exec(ctx, disconnectIntegration, arg.ID, arg.OrganizationID)
	return err
}

const getIntegration = `-- name: GetIntegration :one
SELECT id, organization_id, provider, status, external_user_id, display_name, scopes, access_token_encrypted, refresh_token_encrypted, token_expires_at, last_error, created_by, created_at, updated_at, metadata, last_discovered_at, disconnected_at FROM integrations
WHERE id = $1 AND organization_id = $2
`

type GetIntegrationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) GetIntegration(ctx context.Context, arg GetIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, arg.ID, arg.OrganizationID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Scopes,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.LastDiscoveredAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, organization_id, provider, status, external_user_id, display_name, scopes, access_token_encrypted, refresh_token_encrypted, token_expires_at, last_error, created_by, created_at, updated_at, metadata, last_discovered_at, disconnected_at FROM integrations WHERE id = $1
`

func (q *Queries) GetIntegrationByID(ctx context.Context, id uuid.UUID) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Scopes,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.LastDiscoveredAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const listActiveIntegrations = `-- name: ListActiveIntegrations :many
SELECT id, organization_id FROM integrations
WHERE status = 'active'
ORDER BY id
`

type ListActiveIntegrationsRow struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) ListActiveIntegrations(ctx context.Context) ([]ListActiveIntegrationsRow, error) {
	rows, err := q.db.Query(ctx, listActiveIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveIntegrationsRow{}
	for rows.Next() {
		var i ListActiveIntegrationsRow
		if err := rows.Scan(&i.ID, &i.OrganizationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, organization_id, provider, status, external_user_id, display_name, scopes, access_token_encrypted, refresh_token_encrypted, token_expires_at, last_error, created_by, created_at, updated_at, metadata, last_discovered_at, disconnected_at FROM integrations
WHERE organization_id = $1
ORDER BY created_at
`

func (q *Queries) ListIntegrations(ctx context.Context, organizationID uuid.UUID) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Provider,
			&i.Status,
			&i.ExternalUserID,
			&i.DisplayName,
			&i.Scopes,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
			&i.TokenExpiresAt,
			&i.LastError,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Metadata,
			&i.LastDiscoveredAt,
			&i.DisconnectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncEnabledAccounts = `-- name: ListSyncEnabledAccounts :many
SELECT external_id FROM ad_accounts
WHERE integration_id = $1 AND organization_id = $2 AND sync_enabled
ORDER BY external_id
`

type ListSyncEnabledAccountsParams struct {
	IntegrationID  *uuid.UUID `json:"integration_id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
}

// Accounts an admin opted in to syncing (ad_accounts is owned by the entities package).
func (q *Queries) ListSyncEnabledAccounts(ctx context.Context, arg ListSyncEnabledAccountsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSyncEnabledAccounts, arg.IntegrationID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var external_id string
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIntegration = `-- name: LockIntegration :one
SELECT id, organization_id, provider, status, external_user_id, display_name, scopes, access_token_encrypted, refresh_token_encrypted, token_expires_at, last_error, created_by, created_at, updated_at, metadata, last_discovered_at, disconnected_at FROM integrations
WHERE id = $1 AND organization_id = $2
FOR UPDATE
`

type LockIntegrationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) LockIntegration(ctx context.Context, arg LockIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, lockIntegration, arg.ID, arg.OrganizationID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Scopes,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.LastDiscoveredAt,
		&i.DisconnectedAt,
	)
	return i, err
}

const markIntegrationNeedsReauth = `-- name: MarkIntegrationNeedsReauth :exec
UPDATE integrations
SET status = 'needs_reauth', last_error = $1, updated_at = now()
WHERE id = $2 AND status = 'active'
`

type MarkIntegrationNeedsReauthParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) MarkIntegrationNeedsReauth(ctx context.Context, arg MarkIntegrationNeedsReauthParams) error {
	_, err := q.db.Exec(ctx, markIntegrationNeedsReauth, arg.LastError, arg.ID)
	return err
}

const recordIntegrationDiscovery = `-- name: RecordIntegrationDiscovery :exec
UPDATE integrations
SET metadata = $1, last_discovered_at = now(), last_error = NULL, updated_at = now()
WHERE id = $2
`

type RecordIntegrationDiscoveryParams struct {
	Metadata []byte    `json:"metadata"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) RecordIntegrationDiscovery(ctx context.Context, arg RecordIntegrationDiscoveryParams) error {
	_, err := q.db.Exec(ctx, recordIntegrationDiscovery, arg.Metadata, arg.ID)
	return err
}

const setIntegrationError = `-- name: SetIntegrationError :exec
UPDATE integrations
SET last_error = $1, updated_at = now()
WHERE id = $2
`

type SetIntegrationErrorParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) SetIntegrationError(ctx context.Context, arg SetIntegrationErrorParams) error {
	_, err := q.db.Exec(ctx, setIntegrationError, arg.LastError, arg.ID)
	return err
}

const updateIntegrationTokens = `-- name: UpdateIntegrationTokens :exec
UPDATE integrations
SET access_token_encrypted  = $1,
    refresh_token_encrypted = COALESCE($2, refresh_token_encrypted),
    token_expires_at        = $3,
    updated_at              = now()
WHERE id = $4 AND status = 'active'
`

type UpdateIntegrationTokensParams struct {
	AccessTokenEncrypted  []byte     `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte     `json:"refresh_token_encrypted"`
	TokenExpiresAt        *time.Time `json:"token_expires_at"`
	ID                    uuid.UUID  `json:"id"`
}

func (q *Queries) UpdateIntegrationTokens(ctx context.Context, arg UpdateIntegrationTokensParams) error {
	_, err := q.db.Exec(ctx, updateIntegrationTokens,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
		arg.ID,
	)
	return err
}

const upsertIntegration = `-- name: UpsertIntegration :one
INSERT INTO integrations (
    organization_id, provider, status, external_user_id, display_name, scopes,
    access_token_encrypted, refresh_token_encrypted, token_expires_at, created_by
) VALUES (
    $1, $2, 'active', $3, $4, $5,
    $6, $7, $8, $9
)
ON CONFLICT (organization_id, provider, external_user_id) DO UPDATE SET
    status                  = 'active',
    display_name            = EXCLUDED.display_name,
    scopes                  = EXCLUDED.scopes,
    access_token_encrypted  = EXCLUDED.access_token_encrypted,
    refresh_token_encrypted = COALESCE(EXCLUDED.refresh_token_encrypted, integrations.refresh_token_encrypted),
    token_expires_at        = EXCLUDED.token_expires_at,
    last_error              = NULL,
    disconnected_at         = NULL,
    updated_at              = now()
RETURNING id, organization_id, provider, status, external_user_id, display_name, scopes, access_token_encrypted, refresh_token_encrypted, token_expires_at, last_error, created_by, created_at, updated_at, metadata, last_discovered_at, disconnected_at
`

type UpsertIntegrationParams struct {
	OrganizationID        uuid.UUID  `json:"organization_id"`
	Provider              AdProvider `json:"provider"`
	ExternalUserID        string     `json:"external_user_id"`
	DisplayName           string     `json:"display_name"`
	Scopes                []string   `json:"scopes"`
	AccessTokenEncrypted  []byte     `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte     `json:"refresh_token_encrypted"`
	TokenExpiresAt        *time.Time `json:"token_expires_at"`
	CreatedBy             *uuid.UUID `json:"created_by"`
}

// Reconnecting the same provider user re-activates the row with fresh tokens.
// Google omits the refresh token on some re-consents, so an existing one is kept.
func (q *Queries) UpsertIntegration(ctx context.Context, arg UpsertIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, upsertIntegration,
		arg.OrganizationID,
		arg.Provider,
		arg.ExternalUserID,
		arg.DisplayName,
		arg.Scopes,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
		arg.TokenExpiresAt,
		arg.CreatedBy,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Provider,
		&i.Status,
		&i.ExternalUserID,
		&i.DisplayName,
		&i.Scopes,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
		&i.TokenExpiresAt,
		&i.LastError,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Metadata,
		&i.LastDiscoveredAt,
		&i.DisconnectedAt,
	)
	return i, err
}
