// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO organization_invitations (organization_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at
`

type CreateInvitationParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	Email          string           `json:"email"`
	Role           OrganizationRole `json:"role"`
	TokenHash      []byte           `json:"token_hash"`
	InvitedBy      uuid.UUID        `json:"invited_by"`
	ExpiresAt      time.Time        `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenInvitationByTokenHash = `-- name: GetOpenInvitationByTokenHash :one
SELECT id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM organization_invitations
WHERE token_hash = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

func (q *Queries) GetOpenInvitationByTokenHash(ctx context.Context, tokenHash []byte) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getOpenInvitationByTokenHash, tokenHash)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOpenInvitations = `-- name: ListOpenInvitations :many
SELECT id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM organization_invitations
WHERE organization_id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListOpenInvitations(ctx context.Context, organizationID uuid.UUID) ([]OrganizationInvitation, error) {
	rows, err := q.db.Query(ctx, listOpenInvitations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvitation{}
	for rows.Next() {
		var i OrganizationInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE organization_invitations SET accepted_at = now() WHERE id = $1
`

func (q *Queries) MarkInvitationAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, id)
	return err
}

const revokeExpiredOpenInvitation = `-- name: RevokeExpiredOpenInvitation :exec
UPDATE organization_invitations
SET revoked_at = now()
WHERE organization_id = $1 AND email = $2
  AND accepted_at IS NULL AND revoked_at IS NULL
  AND expires_at <= now()
`

type RevokeExpiredOpenInvitationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
}

// Frees the (organization, email) slot held by an expired invitation.
func (q *Queries) RevokeExpiredOpenInvitation(ctx context.Context, arg RevokeExpiredOpenInvitationParams) error {
	_, err := q.db.Exec(ctx, revokeExpiredOpenInvitation, arg.OrganizationID, arg.Email)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :execrows
UPDATE organization_invitations
SET revoked_at = now()
WHERE id = $1 AND organization_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInvitationParams struct {
	ID             uuid.UUID `json:"id"`
	OrganizationID uuid.UUID `json:"organization_id"`
}

func (q *Queries) RevokeInvitation(ctx context.Context, arg RevokeInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvitation, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
