// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdEntityStatus string

const (
	AdEntityStatusActive   AdEntityStatus = "active"
	AdEntityStatusPaused   AdEntityStatus = "paused"
	AdEntityStatusArchived AdEntityStatus = "archived"
	AdEntityStatusDeleted  AdEntityStatus = "deleted"
	AdEntityStatusUnknown  AdEntityStatus = "unknown"
)

func (e *AdEntityStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdEntityStatus(s)
	case string:
		*e = AdEntityStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AdEntityStatus: %T", src)
	}
	return nil
}

type NullAdEntityStatus struct {
	AdEntityStatus AdEntityStatus `json:"ad_entity_status"`
	Valid          bool           `json:"valid"` // Valid is true if AdEntityStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdEntityStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AdEntityStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdEntityStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdEntityStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdEntityStatus), nil
}

type AdProvider string

const (
	AdProviderMeta   AdProvider = "meta"
	AdProviderGoogle AdProvider = "google"
)

func (e *AdProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdProvider(s)
	case string:
		*e = AdProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AdProvider: %T", src)
	}
	return nil
}

type NullAdProvider struct {
	AdProvider AdProvider `json:"ad_provider"`
	Valid      bool       `json:"valid"` // Valid is true if AdProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AdProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdProvider), nil
}

type IntegrationStatus string

const (
	IntegrationStatusActive       IntegrationStatus = "active"
	IntegrationStatusNeedsReauth  IntegrationStatus = "needs_reauth"
	IntegrationStatusDisconnected IntegrationStatus = "disconnected"
)

func (e *IntegrationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntegrationStatus(s)
	case string:
		*e = IntegrationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IntegrationStatus: %T", src)
	}
	return nil
}

type NullIntegrationStatus struct {
	IntegrationStatus IntegrationStatus `json:"integration_status"`
	Valid             bool              `json:"valid"` // Valid is true if IntegrationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntegrationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IntegrationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntegrationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntegrationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntegrationStatus), nil
}

type OrganizationRole string

const (
	OrganizationRoleOwner  OrganizationRole = "owner"
	OrganizationRoleAdmin  OrganizationRole = "admin"
	OrganizationRoleMember OrganizationRole = "member"
)

func (e *OrganizationRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrganizationRole(s)
	case string:
		*e = OrganizationRole(s)
	default:
		return fmt.Errorf("unsupported scan type for OrganizationRole: %T", src)
	}
	return nil
}

type NullOrganizationRole struct {
	OrganizationRole OrganizationRole `json:"organization_role"`
	Valid            bool             `json:"valid"` // Valid is true if OrganizationRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrganizationRole) Scan(value interface{}) error {
	if value == nil {
		ns.OrganizationRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrganizationRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrganizationRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrganizationRole), nil
}

type Ad struct {
	ID                 uuid.UUID      `json:"id"`
	OrganizationID     uuid.UUID      `json:"organization_id"`
	AccountID          uuid.UUID      `json:"account_id"`
	CampaignID         uuid.UUID      `json:"campaign_id"`
	AdGroupID          uuid.UUID      `json:"ad_group_id"`
	Provider           AdProvider     `json:"provider"`
	ExternalID         string         `json:"external_id"`
	Name               string         `json:"name"`
	Status             AdEntityStatus `json:"status"`
	CreativeExternalID string         `json:"creative_external_id"`
	Raw                []byte         `json:"raw"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type AdAccount struct {
	ID             uuid.UUID      `json:"id"`
	OrganizationID uuid.UUID      `json:"organization_id"`
	IntegrationID  *uuid.UUID     `json:"integration_id"`
	Provider       AdProvider     `json:"provider"`
	ExternalID     string         `json:"external_id"`
	Name           string         `json:"name"`
	Currency       string         `json:"currency"`
	Timezone       string         `json:"timezone"`
	Status         AdEntityStatus `json:"status"`
	SyncEnabled    bool           `json:"sync_enabled"`
	Raw            []byte         `json:"raw"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type AdAccountSyncState struct {
	AccountID      uuid.UUID  `json:"account_id"`
	Scope          string     `json:"scope"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	Provider       AdProvider `json:"provider"`
	LastSyncedAt   time.Time  `json:"last_synced_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type AdGroup struct {
	ID                uuid.UUID      `json:"id"`
	OrganizationID    uuid.UUID      `json:"organization_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	CampaignID        uuid.UUID      `json:"campaign_id"`
	Provider          AdProvider     `json:"provider"`
	ExternalID        string         `json:"external_id"`
	Name              string         `json:"name"`
	Status            AdEntityStatus `json:"status"`
	DailyBudgetMicros *int64         `json:"daily_budget_micros"`
	Raw               []byte         `json:"raw"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type AuditLog struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID *uuid.UUID `json:"organization_id"`
	ActorUserID    *uuid.UUID `json:"actor_user_id"`
	Action         string     `json:"action"`
	EntityType     string     `json:"entity_type"`
	EntityID       string     `json:"entity_id"`
	Metadata       []byte     `json:"metadata"`
	CreatedAt      time.Time  `json:"created_at"`
}

type Campaign struct {
	ID                   uuid.UUID      `json:"id"`
	OrganizationID       uuid.UUID      `json:"organization_id"`
	AccountID            uuid.UUID      `json:"account_id"`
	Provider             AdProvider     `json:"provider"`
	ExternalID           string         `json:"external_id"`
	Name                 string         `json:"name"`
	Status               AdEntityStatus `json:"status"`
	Objective            string         `json:"objective"`
	DailyBudgetMicros    *int64         `json:"daily_budget_micros"`
	LifetimeBudgetMicros *int64         `json:"lifetime_budget_micros"`
	Raw                  []byte         `json:"raw"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
}

type Creative struct {
	ID             uuid.UUID  `json:"id"`
	OrganizationID uuid.UUID  `json:"organization_id"`
	AccountID      uuid.UUID  `json:"account_id"`
	Provider       AdProvider `json:"provider"`
	ExternalID     string     `json:"external_id"`
	Name           string     `json:"name"`
	Type           string     `json:"type"`
	ThumbnailUrl   string     `json:"thumbnail_url"`
	Raw            []byte     `json:"raw"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

type Integration struct {
	ID                    uuid.UUID         `json:"id"`
	OrganizationID        uuid.UUID         `json:"organization_id"`
	Provider              AdProvider        `json:"provider"`
	Status                IntegrationStatus `json:"status"`
	ExternalUserID        string            `json:"external_user_id"`
	DisplayName           string            `json:"display_name"`
	Scopes                []string          `json:"scopes"`
	AccessTokenEncrypted  []byte            `json:"access_token_encrypted"`
	RefreshTokenEncrypted []byte            `json:"refresh_token_encrypted"`
	TokenExpiresAt        *time.Time        `json:"token_expires_at"`
	LastError             *string           `json:"last_error"`
	CreatedBy             *uuid.UUID        `json:"created_by"`
	CreatedAt             time.Time         `json:"created_at"`
	UpdatedAt             time.Time         `json:"updated_at"`
	Metadata              []byte            `json:"metadata"`
	LastDiscoveredAt      *time.Time        `json:"last_discovered_at"`
	DisconnectedAt        *time.Time        `json:"disconnected_at"`
}

type MetricFact struct {
	OrganizationID        uuid.UUID   `json:"organization_id"`
	AccountID             uuid.UUID   `json:"account_id"`
	Provider              AdProvider  `json:"provider"`
	Report                string      `json:"report"`
	Date                  pgtype.Date `json:"date"`
	Hour                  *int16      `json:"hour"`
	CampaignExternalID    string      `json:"campaign_external_id"`
	AdGroupExternalID     string      `json:"ad_group_external_id"`
	AdExternalID          string      `json:"ad_external_id"`
	CreativeExternalID    string      `json:"creative_external_id"`
	Country               string      `json:"country"`
	Device                string      `json:"device"`
	Placement             string      `json:"placement"`
	PublisherPlatform     string      `json:"publisher_platform"`
	Keyword               string      `json:"keyword"`
	SearchTerm            string      `json:"search_term"`
	Currency              string      `json:"currency"`
	Impressions           int64       `json:"impressions"`
	Reach                 *int64      `json:"reach"`
	Clicks                int64       `json:"clicks"`
	SpendMicros           int64       `json:"spend_micros"`
	Conversions           float64     `json:"conversions"`
	ConversionValueMicros int64       `json:"conversion_value_micros"`
	ProviderData          []byte      `json:"provider_data"`
	UpdatedAt             time.Time   `json:"updated_at"`
	DimsHash              []byte      `json:"dims_hash"`
}

type Organization struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type OrganizationInvitation struct {
	ID             uuid.UUID        `json:"id"`
	OrganizationID uuid.UUID        `json:"organization_id"`
	Email          string           `json:"email"`
	Role           OrganizationRole `json:"role"`
	TokenHash      []byte           `json:"token_hash"`
	InvitedBy      uuid.UUID        `json:"invited_by"`
	ExpiresAt      time.Time        `json:"expires_at"`
	AcceptedAt     *time.Time       `json:"accepted_at"`
	RevokedAt      *time.Time       `json:"revoked_at"`
	CreatedAt      time.Time        `json:"created_at"`
}

type OrganizationUser struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	UserID         uuid.UUID        `json:"user_id"`
	Role           OrganizationRole `json:"role"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
}

type Session struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	TokenHash  []byte    `json:"token_hash"`
	UserAgent  string    `json:"user_agent"`
	IpAddress  string    `json:"ip_address"`
	ExpiresAt  time.Time `json:"expires_at"`
	LastSeenAt time.Time `json:"last_seen_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
