// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addOrganizationUser = `-- name: AddOrganizationUser :exec
INSERT INTO organization_users (organization_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddOrganizationUserParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	UserID         uuid.UUID        `json:"user_id"`
	Role           OrganizationRole `json:"role"`
}

func (q *Queries) AddOrganizationUser(ctx context.Context, arg AddOrganizationUserParams) error {
	_, err := q.db.Exec(ctx, addOrganizationUser, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM organization_users
WHERE organization_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (name, slug)
VALUES ($1, $2)
RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembership = `-- name: GetMembership :one
SELECT organization_id, user_id, role, created_at, updated_at FROM organization_users
WHERE organization_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.OrganizationID, arg.UserID)
	var i OrganizationUser
	err := row.Scan(
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, name, slug, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganization(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isMemberByEmail = `-- name: IsMemberByEmail :one
SELECT EXISTS (
    SELECT 1 FROM organization_users
    JOIN users ON users.id = organization_users.user_id
    WHERE organization_users.organization_id = $1 AND users.email = $2
)
`

type IsMemberByEmailParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
}

func (q *Queries) IsMemberByEmail(ctx context.Context, arg IsMemberByEmailParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMemberByEmail, arg.OrganizationID, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMembers = `-- name: ListMembers :many
SELECT users.id, users.email, users.name, organization_users.role, organization_users.created_at
FROM organization_users
JOIN users ON users.id = organization_users.user_id
WHERE organization_users.organization_id = $1
ORDER BY organization_users.created_at
`

type ListMembersRow struct {
	ID        uuid.UUID        `json:"id"`
	Email     string           `json:"email"`
	Name      string           `json:"name"`
	Role      OrganizationRole `json:"role"`
	CreatedAt time.Time        `json:"created_at"`
}

func (q *Queries) ListMembers(ctx context.Context, organizationID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT organizations.id, organizations.name, organizations.slug, organizations.created_at, organizations.updated_at, organization_users.role
FROM organizations
JOIN organization_users ON organization_users.organization_id = organizations.id
WHERE organization_users.user_id = $1
ORDER BY organizations.name
`

type ListOrganizationsForUserRow struct {
	Organization Organization     `json:"organization"`
	Role         OrganizationRole `json:"role"`
}

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsForUserRow{}
	for rows.Next() {
		var i ListOrganizationsForUserRow
		if err := rows.Scan(
			&i.Organization.ID,
			&i.Organization.Name,
			&i.Organization.Slug,
			&i.Organization.CreatedAt,
			&i.Organization.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrganization = `-- name: LockOrganization :exec
SELECT id FROM organizations WHERE id = $1 FOR UPDATE
`

// Serialises membership changes so the last-owner check cannot race.
func (q *Queries) LockOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockOrganization, id)
	return err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM organization_users
WHERE organization_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.OrganizationID, arg.UserID)
	return err
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE organization_users
SET role = $3, updated_at = now()
WHERE organization_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	OrganizationID uuid.UUID        `json:"organization_id"`
	UserID         uuid.UUID        `json:"user_id"`
	Role           OrganizationRole `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.OrganizationID, arg.UserID, arg.Role)
	return err
}
