// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createImpersonationSession = `-- name: CreateImpersonationSession :one
INSERT INTO sessions (user_id, token_hash, user_agent, ip_address, expires_at, impersonator_user_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, token_hash, user_agent, ip_address, expires_at, last_seen_at, created_at, impersonator_user_id
`

type CreateImpersonationSessionParams struct {
	UserID             uuid.UUID  `json:"user_id"`
	TokenHash          []byte     `json:"token_hash"`
	UserAgent          string     `json:"user_agent"`
	IpAddress          string     `json:"ip_address"`
	ExpiresAt          time.Time  `json:"expires_at"`
	ImpersonatorUserID *uuid.UUID `json:"impersonator_user_id"`
}

func (q *Queries) CreateImpersonationSession(ctx context.Context, arg CreateImpersonationSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createImpersonationSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
		arg.ImpersonatorUserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ImpersonatorUserID,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, user_agent, ip_address, expires_at, last_seen_at, created_at, impersonator_user_id
`

type CreateSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	UserAgent string    `json:"user_agent"`
	IpAddress string    `json:"ip_address"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.ImpersonatorUserID,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :execrows
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessions, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionUserByTokenHash = `-- name: GetSessionUserByTokenHash :one
SELECT
    sessions.id AS session_id,
    sessions.expires_at,
    sessions.last_seen_at,
    sessions.impersonator_user_id,
    users.id, users.email, users.name, users.password_hash, users.created_at, users.updated_at, users.is_platform_admin
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.expires_at > now()
`

type GetSessionUserByTokenHashRow struct {
	SessionID          uuid.UUID  `json:"session_id"`
	ExpiresAt          time.Time  `json:"expires_at"`
	LastSeenAt         time.Time  `json:"last_seen_at"`
	ImpersonatorUserID *uuid.UUID `json:"impersonator_user_id"`
	User               User       `json:"user"`
}

func (q *Queries) GetSessionUserByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionUserByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionUserByTokenHash, tokenHash)
	var i GetSessionUserByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.ImpersonatorUserID,
		&i.User.ID,
		&i.User.Email,
		&i.User.Name,
		&i.User.PasswordHash,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.IsPlatformAdmin,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
